name: McDefcon
main: com.systexpro.defcon.McDefcon
version: 3.0
permissions:
    mcdefcon.admin:
        description: Allows a Player to change Defcon Levels
        default: false
    mcdefcon.accept:
        description: Allows a Player to bypass Defcon Levels
        default: false
commands:
  dc:
    description: Defcon Command Trigger
    usage: /<command> 
  defcon:
    description: Defcon Command Trigger
    usage: /<command>